# .github/workflows/actions.yml

name: Update Weather Data

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py to generate weather data
        run: python main.py

      - name: Check if the weather file was generated
        run: |
          if [ -f dehiwala_weather_updates.js ]; then
            echo "dehiwala_weather_updates.js exists"
            cat dehiwala_weather_updates.js
          else
            echo "dehiwala_weather_updates.js does not exist"
            exit 1
          fi

      - name: Commit and push weather updates (if changed)
        run: |
          git config --local user.email "rohangunatilake@gmail.com"
          git config --local user.name "MiyuruG"
          git add dehiwala_weather_updates.js
          git diff --cached --quiet || (git commit --allow-empty -m "Update weather" && git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git)
